site:
  title: Spring Session
  url: https://docs.spring.io/spring-session/reference/
asciidoc:
  attributes:
    page-pagination: true
content:
  sources:
    - url: https://github.com/spring-io/spring-generated-docs
      branches: [spring-projects/spring-session/3.0.0-M3,spring-projects/spring-session/main,'spring-projects/spring-session/2.6.*', 'spring-projects/spring-session/2.7.*']
    - url: https://github.com/spring-projects/spring-session
      branches: [main,2.6.x,2.7.x]
      tags: ['3.*','2.6.*','2.7.*','!2.6.0-M*','!2.6.0-R*','!2.7.0-M*','!3.0.0-M1','!3.0.0-M2']
      start_path: spring-session-docs
urls:
  latest_version_segment_strategy: redirect:to
  latest_version_segment: ''
  redirect_facility: httpd
ui:
  bundle:
    url: https://github.com/spring-io/antora-ui-spring/releases/download/latest/ui-bundle.zip
    snapshot: true

antora:
  extensions:
    - require: ./antora/extensions/version-fix.js
    - require: ./antora/extensions/major-minor-segment.js
