site:
  title: Spring Session
  start_page: session::index.adoc
content:
  sources:
    - url: https://github.com/spring-io/spring-generated-docs
      branches: [spring-session/main]
    - url: ./
      branches: HEAD
      start_path: spring-session-docs
ui:
  bundle:
    url: https://github.com/spring-io/antora-ui-spring/releases/download/latest/ui-bundle.zip
    snapshot: true
